# Generated by Django 4.2.1 on 2023-05-15 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artyweb', '0006_alter_panier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeprojet',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artyweb.projet'),
        ),
        migrations.AlterField(
            model_name='demandeprojet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='demandeprojet',
            name='libelle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
