# Generated by Django 4.2.1 on 2023-05-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyweb', '0007_demandeprojet_projet_alter_demandeprojet_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeprojet',
            name='projet',
        ),
        migrations.AlterField(
            model_name='demandeprojet',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='demandeprojet',
            name='libelle',
            field=models.CharField(max_length=50),
        ),
    ]
