# Generated by Django 4.2.1 on 2023-05-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyweb', '0009_alter_panier_date_ajout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeprojet',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='EA', max_length=20),
        ),
    ]
