# Generated by Django 4.2.1 on 2023-05-15 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artyweb', '0010_alter_demandeprojet_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artyweb.client'),
        ),
        migrations.AlterField(
            model_name='demandeprojet',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], max_length=20),
        ),
    ]
